### ISSUE TITLE
`#reload` doesn't raise `ActiveRecord::RecordNotFound` for soft deleted objects

### ISSUE THREAD

**Issue by boxofrad** [ActsAsParanoid/acts_as_paranoid#33]
Hey there!

Not sure if this is a bug or the intended behaviour, but we had a test that looked a little like this:

```ruby
it 'deletes the book' do
  delete :destroy, id: book.id
  expect { book.reload }.to raise_error ActiveRecord::RecordNotFound
end
```

Which worked without `acts_as_paranoid` but fails with it because `#reload` doesn't raise `ActiveRecord::RecordNotFound` for soft deleted objects.

We can work around this by changing our assertion to this:

```ruby
expect { Book.find(book.id) }.to raise_error ActiveRecord::RecordNotFound
```

But I thought it may be worth discussion / what do you think?

Thanks! :sparkling_heart:

**Comment by zzak** [comment]
Do you still have this problem after upgrading?

Thanks

**Comment by boxofrad** [comment]
@zzak Thanks for getting back to me :smile: 
I actually no longer work on the project anymore so couldn't tell you!

Feel free to close

**Comment by zzak** [comment]
@boxofrad FWIW, I think this is unexpected behavior but probably because using `reload` is effectively doing the right thing. I would also assume that nowhere in an application can you "reload" a soft-deleted object that is still in memory, so this is really a non-issue. AR will always do a `find` on the class and your application should raise a `RecordNotFound` exception unless you specify `with_deleted` and the object is soft-deleted.
