### ISSUE TITLE
deleted_at always set date "2000-01-01 XX:XX:XX" 

### ISSUE THREAD

**Issue by jhadeepakkumar14** [ActsAsParanoid/acts_as_paranoid#97]
Whenever I am deleting my record, it sets deleted_at to "2000-01-01 XX:XX:XX" (XX is some timestamp). I did not find any issue on the list for this if there is an issue created for this before then link this issue to that. And please help me to figure out this issue. Thanks

**Comment by jfiander** [comment]
Quick reaction: That looks like the column type may be `time`, rather than `datetime`. It essentially throws out the date, hence the 1/1/00 "date". Take a look – hopefully it's that simple.

**Comment by mvz** [comment]
@jhadeepakkumar14 can you confirm @jfiander analysis?

**Comment by jhadeepakkumar14** [comment]
@mvz Yes. I am using mysql db, and datatype was time. I tried using datetime. it works. Thanks @jfiander and @mvz

**Comment by mvz** [comment]
@gamesover `time` is just a flag for `acts_as_paranoid` to use time-like semantics, rather than, say, boolean. It's a little confusing since the corresponding database field type should indeed be datetime.

It makes a little more sense if you consider that Ruby's `Time` class also includes the date.

**Comment by mvz** [comment]
We can probably change the README to make this a little clearer, e.g., by first introducing the options and their meaning formally, and explaining the difference between the option value and the database column type.

**Comment by ritec** [comment]
Hdd this same problem and it was indeed the column type. in order to solve it and attempt to retrieve the correct deleted_at dates I did the following in a migration:

```
    execute <<-SQL
      ALTER TABLE questions ALTER COLUMN deleted_at TYPE timestamp without time zone
        USING CASE WHEN deleted_at IS NOT NULL THEN updated_at END;
    SQL
```

Because the deleted_at was more than likely the last thing that was updated when the record was soft deleted, so the `updated_at` probably has the correct date.

**Comment by mvz** [comment]
The README has been updated to clarify this.
